/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionCategory = IDL.Variant({
  'service' : IDL.Null,
  'subscription' : IDL.Null,
  'other' : IDL.Null,
  'sales' : IDL.Null,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
});
export const TransactionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'date' : Timestamp,
  'description' : IDL.Text,
  'category' : TransactionCategory,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'viewer' : IDL.Null,
});
export const CreateUserRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const UserId = IDL.Nat;
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'joinDate' : Timestamp,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const DashboardKPIs = IDL.Record({
  'activeUsers' : IDL.Nat,
  'revenueYesterday' : IDL.Nat,
  'revenueToday' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'revenueThisWeek' : IDL.Nat,
});
export const ActivityEventKind = IDL.Variant({
  'user_created' : IDL.Null,
  'user_deactivated' : IDL.Null,
  'transaction_added' : IDL.Null,
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Nat,
  'kind' : ActivityEventKind,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const RevenueAggregates = IDL.Record({
  'revenueYesterday' : IDL.Nat,
  'revenueToday' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'revenueThisWeek' : IDL.Nat,
});
export const TransactionPage = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Transaction),
});
export const UpdateUserRequest = IDL.Record({
  'status' : IDL.Opt(UserStatus),
  'name' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(UserRole),
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addTransaction' : IDL.Func(
      [IDL.Nat, TransactionCategory, TransactionStatus, IDL.Text],
      [Transaction],
      [],
    ),
  'createUser' : IDL.Func([CreateUserRequest], [UserPublic], []),
  'deleteUser' : IDL.Func([UserId], [IDL.Bool], []),
  'getDashboardKPIs' : IDL.Func([], [DashboardKPIs], ['query']),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getRevenueAggregates' : IDL.Func([], [RevenueAggregates], ['query']),
  'getTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Opt(Transaction)],
      ['query'],
    ),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'listTransactions' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [TransactionPage],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserPublic)], ['query']),
  'updateUser' : IDL.Func(
      [UserId, UpdateUserRequest],
      [IDL.Opt(UserPublic)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionCategory = IDL.Variant({
    'service' : IDL.Null,
    'subscription' : IDL.Null,
    'other' : IDL.Null,
    'sales' : IDL.Null,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
  });
  const TransactionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'date' : Timestamp,
    'description' : IDL.Text,
    'category' : TransactionCategory,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'viewer' : IDL.Null });
  const CreateUserRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const UserId = IDL.Nat;
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'joinDate' : Timestamp,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const DashboardKPIs = IDL.Record({
    'activeUsers' : IDL.Nat,
    'revenueYesterday' : IDL.Nat,
    'revenueToday' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'revenueThisWeek' : IDL.Nat,
  });
  const ActivityEventKind = IDL.Variant({
    'user_created' : IDL.Null,
    'user_deactivated' : IDL.Null,
    'transaction_added' : IDL.Null,
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Nat,
    'kind' : ActivityEventKind,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const RevenueAggregates = IDL.Record({
    'revenueYesterday' : IDL.Nat,
    'revenueToday' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'revenueThisWeek' : IDL.Nat,
  });
  const TransactionPage = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Transaction),
  });
  const UpdateUserRequest = IDL.Record({
    'status' : IDL.Opt(UserStatus),
    'name' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(UserRole),
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addTransaction' : IDL.Func(
        [IDL.Nat, TransactionCategory, TransactionStatus, IDL.Text],
        [Transaction],
        [],
      ),
    'createUser' : IDL.Func([CreateUserRequest], [UserPublic], []),
    'deleteUser' : IDL.Func([UserId], [IDL.Bool], []),
    'getDashboardKPIs' : IDL.Func([], [DashboardKPIs], ['query']),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getRevenueAggregates' : IDL.Func([], [RevenueAggregates], ['query']),
    'getTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Opt(Transaction)],
        ['query'],
      ),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'listTransactions' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [TransactionPage],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserPublic)], ['query']),
    'updateUser' : IDL.Func(
        [UserId, UpdateUserRequest],
        [IDL.Opt(UserPublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };