/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'id' : bigint,
  'kind' : ActivityEventKind,
  'description' : string,
  'timestamp' : bigint,
}
export type ActivityEventKind = { 'user_created' : null } |
  { 'user_deactivated' : null } |
  { 'transaction_added' : null };
export interface CreateUserRequest {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export interface DashboardKPIs {
  'activeUsers' : bigint,
  'revenueYesterday' : bigint,
  'revenueToday' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'revenueThisWeek' : bigint,
}
export interface RevenueAggregates {
  'revenueYesterday' : bigint,
  'revenueToday' : bigint,
  'totalRevenue' : bigint,
  'revenueThisWeek' : bigint,
}
export type Timestamp = bigint;
export interface Transaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'date' : Timestamp,
  'description' : string,
  'category' : TransactionCategory,
  'amount' : bigint,
}
export type TransactionCategory = { 'service' : null } |
  { 'subscription' : null } |
  { 'other' : null } |
  { 'sales' : null };
export type TransactionId = bigint;
export interface TransactionPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Transaction>,
}
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null };
export interface UpdateUserRequest {
  'status' : [] | [UserStatus],
  'name' : [] | [string],
  'role' : [] | [UserRole],
  'email' : [] | [string],
}
export type UserId = bigint;
export interface UserPublic {
  'id' : UserId,
  'status' : UserStatus,
  'joinDate' : Timestamp,
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'viewer' : null };
export type UserStatus = { 'active' : null } |
  { 'inactive' : null };
export interface _SERVICE {
  'addTransaction' : ActorMethod<
    [bigint, TransactionCategory, TransactionStatus, string],
    Transaction
  >,
  'createUser' : ActorMethod<[CreateUserRequest], UserPublic>,
  'deleteUser' : ActorMethod<[UserId], boolean>,
  'getDashboardKPIs' : ActorMethod<[], DashboardKPIs>,
  'getRecentActivity' : ActorMethod<[], Array<ActivityEvent>>,
  'getRevenueAggregates' : ActorMethod<[], RevenueAggregates>,
  'getTransaction' : ActorMethod<[TransactionId], [] | [Transaction]>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'listTransactions' : ActorMethod<[bigint, bigint], TransactionPage>,
  'listUsers' : ActorMethod<[], Array<UserPublic>>,
  'searchUsers' : ActorMethod<[string], Array<UserPublic>>,
  'updateUser' : ActorMethod<[UserId, UpdateUserRequest], [] | [UserPublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];