/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UserPublic {
    id: UserId;
    status: UserStatus;
    joinDate: Timestamp;
    name: string;
    role: UserRole;
    email: string;
}
export interface CreateUserRequest {
    name: string;
    role: UserRole;
    email: string;
}
export interface TransactionPage {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Transaction>;
}
export interface Transaction {
    id: TransactionId;
    status: TransactionStatus;
    date: Timestamp;
    description: string;
    category: TransactionCategory;
    amount: bigint;
}
export type UserId = bigint;
export type TransactionId = bigint;
export interface ActivityEvent {
    id: bigint;
    kind: ActivityEventKind;
    description: string;
    timestamp: bigint;
}
export interface RevenueAggregates {
    revenueYesterday: bigint;
    revenueToday: bigint;
    totalRevenue: bigint;
    revenueThisWeek: bigint;
}
export interface UpdateUserRequest {
    status?: UserStatus;
    name?: string;
    role?: UserRole;
    email?: string;
}
export interface DashboardKPIs {
    activeUsers: bigint;
    revenueYesterday: bigint;
    revenueToday: bigint;
    totalUsers: bigint;
    totalRevenue: bigint;
    revenueThisWeek: bigint;
}
export enum ActivityEventKind {
    user_created = "user_created",
    user_deactivated = "user_deactivated",
    transaction_added = "transaction_added"
}
export enum TransactionCategory {
    service = "service",
    subscription = "subscription",
    other = "other",
    sales = "sales"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded"
}
export enum UserRole {
    admin = "admin",
    viewer = "viewer"
}
export enum UserStatus {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    addTransaction(amount: bigint, category: TransactionCategory, status: TransactionStatus, description: string): Promise<Transaction>;
    createUser(req: CreateUserRequest): Promise<UserPublic>;
    deleteUser(id: UserId): Promise<boolean>;
    getDashboardKPIs(): Promise<DashboardKPIs>;
    getRecentActivity(): Promise<Array<ActivityEvent>>;
    getRevenueAggregates(): Promise<RevenueAggregates>;
    getTransaction(id: TransactionId): Promise<Transaction | null>;
    getUser(id: UserId): Promise<UserPublic | null>;
    listTransactions(offset: bigint, limit: bigint): Promise<TransactionPage>;
    listUsers(): Promise<Array<UserPublic>>;
    searchUsers(searchTerm: string): Promise<Array<UserPublic>>;
    updateUser(id: UserId, req: UpdateUserRequest): Promise<UserPublic | null>;
}
import type { ActivityEvent as _ActivityEvent, ActivityEventKind as _ActivityEventKind, CreateUserRequest as _CreateUserRequest, Timestamp as _Timestamp, Transaction as _Transaction, TransactionCategory as _TransactionCategory, TransactionId as _TransactionId, TransactionPage as _TransactionPage, TransactionStatus as _TransactionStatus, UpdateUserRequest as _UpdateUserRequest, UserId as _UserId, UserPublic as _UserPublic, UserRole as _UserRole, UserStatus as _UserStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTransaction(arg0: bigint, arg1: TransactionCategory, arg2: TransactionStatus, arg3: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, to_candid_TransactionCategory_n1(this._uploadFile, this._downloadFile, arg1), to_candid_TransactionStatus_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Transaction_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, to_candid_TransactionCategory_n1(this._uploadFile, this._downloadFile, arg1), to_candid_TransactionStatus_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Transaction_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: CreateUserRequest): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(to_candid_CreateUserRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(to_candid_CreateUserRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getDashboardKPIs(): Promise<DashboardKPIs> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardKPIs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardKPIs();
            return result;
        }
    }
    async getRecentActivity(): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivity();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivity();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueAggregates(): Promise<RevenueAggregates> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueAggregates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueAggregates();
            return result;
        }
    }
    async getTransaction(arg0: TransactionId): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransactions(arg0: bigint, arg1: bigint): Promise<TransactionPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactions(arg0, arg1);
                return from_candid_TransactionPage_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactions(arg0, arg1);
            return from_candid_TransactionPage_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UserId, arg1: UpdateUserRequest): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_UpdateUserRequest_n32(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_UpdateUserRequest_n32(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityEventKind_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEventKind): ActivityEventKind {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityEvent_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEvent): ActivityEvent {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionCategory): TransactionCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionPage_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionPage): TransactionPage {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    joinDate: _Timestamp;
    name: string;
    role: _UserRole;
    email: string;
}): {
    id: UserId;
    status: UserStatus;
    joinDate: Timestamp;
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n17(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: from_candid_UserRole_n19(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _ActivityEventKind;
    description: string;
    timestamp: bigint;
}): {
    id: bigint;
    kind: ActivityEventKind;
    description: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        kind: from_candid_ActivityEventKind_n24(_uploadFile, _downloadFile, value.kind),
        description: value.description,
        timestamp: value.timestamp
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Transaction>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Transaction>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n30(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    status: _TransactionStatus;
    date: _Timestamp;
    description: string;
    category: _TransactionCategory;
    amount: bigint;
}): {
    id: TransactionId;
    status: TransactionStatus;
    date: Timestamp;
    description: string;
    category: TransactionCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n7(_uploadFile, _downloadFile, value.status),
        date: value.date,
        description: value.description,
        category: from_candid_TransactionCategory_n9(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: null;
} | {
    subscription: null;
} | {
    other: null;
} | {
    sales: null;
}): TransactionCategory {
    return "service" in value ? TransactionCategory.service : "subscription" in value ? TransactionCategory.subscription : "other" in value ? TransactionCategory.other : "sales" in value ? TransactionCategory.sales : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "inactive" in value ? UserStatus.inactive : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    viewer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "viewer" in value ? UserRole.viewer : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user_created: null;
} | {
    user_deactivated: null;
} | {
    transaction_added: null;
}): ActivityEventKind {
    return "user_created" in value ? ActivityEventKind.user_created : "user_deactivated" in value ? ActivityEventKind.user_deactivated : "transaction_added" in value ? ActivityEventKind.transaction_added : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "refunded" in value ? TransactionStatus.refunded : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEvent>): Array<ActivityEvent> {
    return value.map((x)=>from_candid_ActivityEvent_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n15(_uploadFile, _downloadFile, x));
}
function to_candid_CreateUserRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateUserRequest): _CreateUserRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): _TransactionCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): _TransactionStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserRequest): _UpdateUserRequest {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n13(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: UserStatus;
    name?: string;
    role?: UserRole;
    email?: string;
}): {
    status: [] | [_UserStatus];
    name: [] | [string];
    role: [] | [_UserRole];
    email: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_UserStatus_n34(_uploadFile, _downloadFile, value.status)) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        role: value.role ? candid_some(to_candid_UserRole_n13(_uploadFile, _downloadFile, value.role)) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    viewer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): {
    service: null;
} | {
    subscription: null;
} | {
    other: null;
} | {
    sales: null;
} {
    return value == TransactionCategory.service ? {
        service: null
    } : value == TransactionCategory.subscription ? {
        subscription: null
    } : value == TransactionCategory.other ? {
        other: null
    } : value == TransactionCategory.sales ? {
        sales: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} {
    return value == TransactionStatus.pending ? {
        pending: null
    } : value == TransactionStatus.completed ? {
        completed: null
    } : value == TransactionStatus.refunded ? {
        refunded: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
